version: "3.9"

services:
  redis:
    image: redis:8
    container_name: redis-geo
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--save"
      - "60"
      - "1000"
    ports:
      - "6379:6379"
    volumes:
      - ./.redis:/.data
    networks:
      - redcat-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5540:5540"
    networks:
      - redcat-net
    restart: unless-stopped

  embedder:
    build:
      context: .
      dockerfile: build/embedder.Dockerfile
      args:
        MODEL_DIR: models/e5-multilingual-large/onnx
        MODEL_FILE: model_qint8_avx512_vnni.onnx
    environment:
      EMBEDDER_MODEL_PATH: /app/models/model.onnx
      EMBEDDER_TOKENIZER_PATH: /app/models
      EMBEDDER_MAX_LEN: "128"
    ports:
      - "8081:8000"
    networks:
      - redcat-net
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: build/redcat.Dockerfile
    ports:
      - "8082:8080"
    networks:
      - redcat-net
    restart: unless-stopped

  keplergl:
    image: crazycapivara/kepler.gl:latest
    container_name: keplergl
    environment:
      - MapboxAccessToken=${MAPBOX_TOKEN:-}
    ports:
      - "8080:80"
    networks:
      - redcat-net
    restart: unless-stopped

  data-server:
    image: nginx:alpine
    container_name: data
    volumes:
      - ./data:/usr/share/nginx/html:ro
    ports:
      - "8083:80"
    networks:
      - redcat-net
    restart: unless-stopped


networks:
  redcat-net:
    driver: bridge
